const questions = [
    {
        id: 1,
        question: "Qual é o planeta do sistema solar que fica mais próximo do Sol?",
        option1: "Vênus",
        option2: "Mercúrio",
        option3: "Júpiter",
        option4: "Netuno",
        correct: "Mercúrio",
        dificulty: "Easy",
    },
    {
        id: 2,
        question: "Qual é o nome do cachorro do personagem 'Cebolinha', da Turma da Mônica?",
        option1: "Bidu",
        option2: "Monicão",
        option3: "Floquinho",
        option4: "Chovinista",
        correct: "Floquinho",
        dificulty: "Easy",
    },
    {
        id: 3,
        question: "A área da ciência responsável por estudar os seres-vivos é conhecida por:",
        option1: "Biologia",
        option2: "Geologia",
        option3: "Psicologia",
        option4: "Sociologia",
        correct: "Biologia",
        dificulty: "Easy",
    },
    {
        id: 4,
        question: "Qual ator, em um seriado, já saiu pelado de dentro de um sofá?",
        option1: "Jack Black",
        option2: "Leandro Hassum",
        option3: "Steve Carell",
        option4: "Danny DeVito",
        correct: "Danny DeVito",
        dificulty: "Hard",
    },
    {
        id: 5,
        question: "Qual participante do Reality Show 'Big Brother Brasil' enfrentou mais paredões na história do programa?",
        option1: "Ana Carolina, BBB9",
        option2: "Gilberto Nogueira, BBB21",
        option3: "Babu Santana, BBB20",
        option4: "Arthur Aguiar, BBB22",
        correct: "Babu Santana, BBB20",
        dificulty: "Hard",
    },
    {
        id: 6,
        question: "No desenho animado 'Steven Universo', qual é a fusão resultante das pedras 'Jasper' e 'Lápis-Lazuli'?",
        option1: "Malaquita",
        option2: "Garnet",
        option3: "Quartzo-Fumê",
        option4: "Obsidiana",
        correct: "Malaquita",
        dificulty: "Hard",
    },
]

export default questions;